export default {
  ADD_USERS_SAGA: 'ADD_USERS_SAGA',
  ADD_USERS: 'ADD_USERS',
  EDIT_USER: 'EDIT_USER',
  REMOVE_USER: 'REMOVE_USER',
  ADD_SKILLS: 'ADD_SKILLS',
  EDIT_SKILL: 'EDIT_SKILL',
  REMOVE_SKILL: 'REMOVE_SKILL',
  ADD_USER_CONTEXT: 'ADD_USER_CONTEXT',
  EDIT_USER_CONTEXT: 'EDIT_USER_CONTEXT',
};
